config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end

      resources :questions, except: [:edit, :new] do
        resources :answers, except: [:edit, :new], shallow: true
      end
    end
  end

  get 'search', action: :search, controller: 'search'

  namespace :users do
    get '/set_email', to: 'emails#new'
    post '/set_email', to: 'emails#create'
  end

  concern :voted do
    member do
      put :vote_for
      put :vote_against
      delete :cancel_voting
    end
  end

  concern :commented do
    member do
      post :create_comment
    end
  end

  resources :questions, concerns: [:voted, :commented] do
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, only: %i[create destroy update], concerns: [:voted, :commented], shallow: true do
      member do
        post :mark_as_best
      end
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :users, only: :rewards do
    member do
      get :rewards
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :best_answer, class_name: 'Answer', optional: true

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true
  after_create :create_subscription

  def set_best_answer(answer)
    transaction do
      self.update!(best_answer: answer)
      self.reward&.update!(user: answer.author)
    end
  end

  def create_subscription
    subscriptions.create(user: author)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: %i[show update destroy ]

  authorize_resource

  def index
    @questions = Question.all
    render json: @questions
  end

  def show
    render json: @question, serializer: QuestionFullSerializer
  end

  def create
    @question = current_resource_owner.questions.create(question_params)
    if @question.save
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, @question

    if @question.update(question_params)
      render json: @question, status: :accepted
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @question

    @question.destroy
    render json: { messages: ['Your question deleted'] }
  end
  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def find_question
    @question = Question.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: %i[index show]
  before_action :find_subsription, only: [:show, :edit]
  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @best_answer = question.best_answer
    @other_answers = question.answers.where.not(id: question.best_answer)
    gon.push({question_id: question.id})
  end

  def new
    @question = current_user.questions.new
    @question.links.new
    @question.build_reward
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)
    if question.save
      redirect_to question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    question.update(question_params) if authorize! :update, question
  end

  def destroy
    question.destroy if authorize! :destroy, question
    question.destroy if authorize! :update, question
    redirect_to questions_path
  end

  private

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  def answer
    @answer ||= Answer.new
    @answer.links.new

    @answer
  end

  helper_method :question, :answer

  def question_params
    params.require(:question).permit(
      :title,
      :body, files: [],
      links_attributes: [:name, :url, :_destroy, :id],
      reward_attributes: [:name, :image]
    )
  end

  def find_subsription
    @subscription = question.subscriptions.find_by(user: current_user)
  end

  def publish_question
    return if question.errors.any?

    ActionCable.server.broadcast(
      'questions_channel',
      ApplicationController.render(
        partial: 'questions/question_channel',
        locals: { question: @question }
      )
    )
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_comment_channel.html.slim
.text
  = comment.body

app/views/questions/_form.html.slim
.card-body
  = form_with model: question do |form|
    .card-title
      = form.label :title, class: "form-control"
      = form.text_field :title, class: "form-control"

    .card-title
      = form.label :body, class: "form-control"
      = form.text_area :body, class: "form-control"

    .card-title
      = form.label :files
      = form.file_field :files, multiple: true, class: "form-control"

    = render 'links/form', resource: question, form: form
    = render 'reward_form', form: form

    = form.submit "Ask", class: "btn btn-outline-primary"

app/views/questions/_question.html.slim
id="question-list-item-#{question.id}"
p= link_to question.title, question

.question-errors
  = render 'shared/errors', resource: @question

- if can?(:update, question)
  = link_to 'Edit question',
          '#',
          class: 'edit-question-link btn btn-info btn-sm',
          data: { question_id: question.id },
          remote: true

- if can?(:destroy, question)
  = link_to 'Delete question',
          question_path(question),
          method: :delete,
          class: 'btn btn-danger btn-sm',
          remote: true

- if can?(:update, question)
  = form_with model: question, class: 'hidden', html: { id: "edit-question-#{question.id}" }, local: false do |f|
    p= f.label :title, 'Title'
    = f.text_area :title, class: 'form-control'

    p= f.label :body, 'Your question'
    = f.text_area :body, class: 'form-control'

    p= f.label :files
    br= f.file_field :files, class: 'form-control', multiple: true, direct_upload: true

    = render 'links/form', resource: question, f: f

    = f.submit 'Save'

app/views/questions/_question_partial.html.slim
id="question-list-item-#{question.id}"
p= link_to question.title, question

app/views/questions/_reward_form.html.slim
h4 Reward:
.reward
  = form.fields_for :reward do |r|
    = r.label :name, 'Reward name'
    = r.text_field :name, class: "form-control"

    = r.label :image
    br= r.file_field :image, class: 'form-control', direct_upload: true

app/views/questions/create_comment.js.erb
<% if @comment.persisted? %>
$('.form-question-comment #comment_body').val('');
<% end %>

app/views/questions/index.html.slim
.questions
  - if can?(:create, Question)
    p= link_to 'Ask question', new_question_path, class: 'btn btn-info mt-3 btn-sm'

  h3 Questions
  = render @questions

app/views/questions/new.html.slim
= render 'shared/errors', resource: question

.card
  .card-header.h2.text-center Создать вопрос
  = render 'form'

= link_to 'назад', questions_path

app/views/questions/show.html.slim
.question id="question-#{question.id}"
  h2= question.title
  h3= question.body

  = render 'shared/vote', resource: question
  = render 'links/link', resource: question
  = render 'shared/attachments', resource: question

  .subscription
    = render 'subscriptions/subscription', resource: question

  .question-comments
    h4 Comments:
    = render question.comments

  - if can?(:create, Comment)
    = render 'comments/form_question', resource: question

.answers
  h3 Answers
  - if @question.answers.any?
    - if @question.best_answer
      = render 'answers/best_answer', resource: @question.best_answer
    = render @question.answers

- if can?(:create, Answer)
  h4 Create new answer
  .answer-errors
    = render 'shared/errors', resource: @answer

  = form_with model: [@question, @answer], class: 'new-answer', data: { type: :json }, local: false do |f|

    = f.label :body, 'Your answer'
    = f.text_area :body, class: 'form-control'

    = f.label :files
    br= f.file_field :files, class: 'form-control', multiple: true, direct_upload: true

    .answer-links
      = render 'links/form', resource: @answer, f: f

    = f.submit 'Answer'

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: question %>');
<% if !question.errors.present? %>
  $('#question-list-item-<%= question.id %>').remove()
  $('.questions').append('<%= j render question %>');
<% end %>