config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end

      resources :questions, except: [:edit, :new] do
        resources :answers, except: [:edit, :new], shallow: true
      end
    end
  end

  get 'search', action: :search, controller: 'search'

  namespace :users do
    get '/set_email', to: 'emails#new'
    post '/set_email', to: 'emails#create'
  end

  concern :voted do
    member do
      put :vote_for
      put :vote_against
      delete :cancel_voting
    end
  end

  concern :commented do
    member do
      post :create_comment
    end
  end

  resources :questions, concerns: [:voted, :commented] do
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, only: %i[create destroy update], concerns: [:voted, :commented], shallow: true do
      member do
        post :mark_as_best
      end
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :users, only: :rewards do
    member do
      get :rewards
    end
  end

  mount ActionCable.server => '/cable'
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_authorization_check

  def search
    service = SearchService.new(search_params)
    @result = service.call
  end

  private

  def search_params
    params.permit(:body, :type)
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/search.html.slim
.row.justify-content-center.mt-3
  .col.col-md-6
    .form-group.mt-3
      - if @result.empty?
        h3 No results
      - else
        ul
          - @result.each do |item|
            - if item.is_a?(Answer)
              .question-link = link_to item.question.title, question_path(item.question)
              .answer-body = "#{item.class}: #{ item.body}"
            - elsif item.is_a?(Comment)
              .d-block = link_to item.commentable.body, question_path(item.commentable)
              .d-block ="#{item.class}: #{item.body}"
            - elsif item.is_a?(User)
              .d-block = "#{item.email}"
            - else
              = link_to item.title, question_path(item)