config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end

      resources :questions, except: [:edit, :new] do
        resources :answers, except: [:edit, :new], shallow: true
      end
    end
  end

  get 'search', action: :search, controller: 'search'

  namespace :users do
    get '/set_email', to: 'emails#new'
    post '/set_email', to: 'emails#create'
  end

  concern :voted do
    member do
      put :vote_for
      put :vote_against
      delete :cancel_voting
    end
  end

  concern :commented do
    member do
      post :create_comment
    end
  end

  resources :questions, concerns: [:voted, :commented] do
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, only: %i[create destroy update], concerns: [:voted, :commented], shallow: true do
      member do
        post :mark_as_best
      end
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :users, only: :rewards do
    member do
      get :rewards
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user

    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  def admin_abilities
    can :manage, :all
  end

  def guest_abilities
    can :read, :all
    can :all, User
  end

  def user_abilities
    guest_abilities

    can [:create, :create_comment], [Question, Answer, Comment, Subscription ]
    can [:destroy, :update], [Question, Answer, Subscription], user_id: user.id
    can :destroy, Link, linkable: { user_id: user.id }
    can [:vote_for, :vote_against, :cancel_voting], [Question, Answer] do |votable|
      votable.user_id != user.id
    end
    can :destroy, ActiveStorage::Attachment do |attachment|
      user.author_of?(attachment.record)
    end
    can :mark_as_best, Answer, question: {user_id: user.id}
    can :me, User, user_id: user.id
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  has_many :links, dependent: :destroy, as: :linkable
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  after_commit :send_notification, on: :create

  def send_notification
    NotificationJob.perform_later(self)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, :uid, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates  :body, :user, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates :url, format: {
    with: URI.regexp(%w[http https]),
    message: 'is not a valid URL'
  }

  def gist?
    URI(url).host.include?('gist')
  end

  def read_gist
    client = Octokit::Client.new
    client.gist(URI(url).path.split('/').last).files
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_one :reward, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :best_answer, class_name: 'Answer', optional: true

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :title, :body, presence: true
  after_create :create_subscription

  def set_best_answer(answer)
    transaction do
      self.update!(best_answer: answer)
      self.reward&.update!(user: answer.author)
    end
  end

  def create_subscription
    subscriptions.create(user: author)
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true

  has_one_attached :image

  validates :name, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[github]

  has_many :authorizations, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  def self.find_for_oauth(auth)
    Services::FindForOauth.new(auth).call
  end

  def author?(some_data)
    id == some_data&.user_id
  end

  def create_authorization(auth)
    self.authorizations.create(provider: auth.provider, uid: auth.uid.to_s)
  end

  def subscribed?(question)
    subscriptions.where(question: question).exists?
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates  :value, :user, presence: true
end

app/controllers/files_controller.rb
class FilesController < ApplicationController

  attr_reader :obj

  def destroy
    file_as = ActiveStorage::Attachment.find(params[:id])
    @obj = file_as.record
    if current_user.author?(obj)
      obj.files.find(file_as.id).purge
    end

    obj.reload
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, only: :destroy

  def destroy
    link.destroy if authorize! :destroy, link.linkable
  end

  private

  def link
    @link = Link.find(params[:id])
  end

  helper_method :link
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def rewards
    @rewards = current_user.rewards
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= include_gon %>
    <%= Gon::Base.render_data %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render 'shared/nav' %>

  <%= yield %>
  </body>
</html>

app/views/shared/_attachments.html.slim
- if resource.files.attached?
  - resource.files.each do |file|
    p id="attachment_#{file.id}"
      = link_to file.filename.to_s, url_for(file), target: :blank

      - if can? :destroy, file.record
        = link_to 'Delete file',
                attachment_path(file),
                method: :delete,
                class: 'btn btn-danger btn-sm',
                remote: true

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    - resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_nav.html.slim
.navbar.navbar-expand-lg.navbar-light.bg-light
  .collapse.navbar-collapse
    .li.nav-item.active
      = link_to 'QnA', root_path, class: 'btn mt-3'
    - if current_user
      .li.nav-item
        = link_to 'Rewards', rewards_user_path(current_user), class: 'btn mt-3'
      .li.nav-item
        = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn mt-3'
    - else
      .li.nav-item
        = link_to 'sign in', :new_user_session, class: 'btn mt-3'
      .li.nav-item
        = link_to 'registration', :new_user_registration, class: 'btn mt-3'

  .search
    = form_with url: search_path, local: true, method: :get do |f|
      .d-flex
        = f.text_field :body, class: 'mr-sm-2 form-control'
        = f.select :type, SearchService::TYPES, class: 'form-control'
        = f.submit 'Search', class: 'btn btn-outline-success mx-3'

app/views/shared/_vote.html.slim
.vote
.rating id="rating-#{resource.class.name.underscore}-#{resource.id}"
= "Rating: #{resource.rating}"

- if current_user && !current_user.author_of?(resource)
  .vote-actions
    .d-flex
      .p-2 = link_to '+', polymorphic_path(resource, action: :vote_for),
              method: :put,
              data: { type: :json },
              remote: true,
              class: 'btn btn-success btn-sm'

      .p-2 = link_to '-',
              polymorphic_path(resource, action: :vote_against),
              method: :put,
              data: { type: :json },
              remote: true,
              class: 'btn btn-danger btn-sm'

      .p-2 = link_to 'Cancel voting',
              polymorphic_path(resource, action: :cancel_voting),
              method: :delete,
              data: { type: :json },
              remote: true,
              class: 'btn btn-info btn-sm'