config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  authenticate :user, lambda {|u| u.admin?} do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }

  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :all, on: :collection
      end

      resources :questions, except: [:edit, :new] do
        resources :answers, except: [:edit, :new], shallow: true
      end
    end
  end

  get 'search', action: :search, controller: 'search'

  namespace :users do
    get '/set_email', to: 'emails#new'
    post '/set_email', to: 'emails#create'
  end

  concern :voted do
    member do
      put :vote_for
      put :vote_against
      delete :cancel_voting
    end
  end

  concern :commented do
    member do
      post :create_comment
    end
  end

  resources :questions, concerns: [:voted, :commented] do
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, only: %i[create destroy update], concerns: [:voted, :commented], shallow: true do
      member do
        post :mark_as_best
      end
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :users, only: :rewards do
    member do
      get :rewards
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  has_many :links, dependent: :destroy, as: :linkable
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  after_commit :send_notification, on: :create

  def send_notification
    NotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :answer, only: %i[edit update destroy]
  before_action :question, only: %i[create new]
  before_action :authenticate_user!
  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    @answer = question.answers.new(answer_params)
    answer.author = current_user
    answer.save

    respond_to do |format|
      if @answer.save
        format.json { render json: @answer }
      else
        format.json{ render json: @answer.errors.full_messages, status: :unprocessable_entity}
      end
    end
  end

  def update
    if authorize! :update, answer
      answer.update(answer_params)
      @question = answer.question
    end
  end

  def destroy
    if authorize! :destroy, answer
      @question = answer.question
      answer.destroy
    end
  end

  def mark_as_best
    if authorize! :mark_as_best, answer
      question = answer.question
      answer.question.update(best_answer: answer)
      question.set_best_answer(answer)

      @best_answer = answer
      @other_answers = question.answers.where.not(id: question.best_answer)
    end
  end

  private

  def publish_answer
    return if answer.errors.any?
    ActionCable.server.broadcast("answers/#{params[:question_id]}",
      ApplicationController.render(
        partial: 'answers/answer_channel',
        locals: { question: answer.question, answer: answer, current_user: current_user }
      )
    )
  end

  def answer
    @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : Answer.new
  end

  def question
    @question ||= Question.find(params[:question_id])
  end

  helper_method :question, :answer

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url, :_destroy, :id])
  end

end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: [ :index, :create ]
  before_action :find_answer, only: %i[ show update destroy ]

  authorize_resource

  def index
    @answers = @question.answers
    render json: @answers
  end

  def show
    render json: @answer, serializer: AnswerFullSerializer
  end

  def create
    @answer = @question.answers.create(answer_params)
    @answer.author = current_resource_owner

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, @answer

    if @answer.update(answer_params)
      render json: @answer, status: :accepted
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @answer

    @answer.destroy
    render json: { messages: ['Your answer deleted'] }
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
id="answer-#{answer.id}"
- if answer.persisted? && answer&.not_best_of?(question)

  p= answer.body

  = render 'shared/vote', resource: answer
  = render 'links/link', resource: answer
  = render 'shared/attachments', resource: answer

  .answer-comments id="answer-comments-#{answer.id}"
    h4 Comments:
    = render answer.comments
  - if current_user
    = render 'comments/form_answer', answer: answer

  - if can? :mark_as_best, answer
    = link_to 'Mark as best',
            mark_as_best_answer_path(answer),
            method: :post, remote: true,
            class: 'btn btn-success btn-sm'

  - if can? :update, answer

    = link_to 'Edit', '#', class: 'edit-answer-link btn btn-info btn-sm', data: { answer_id: answer.id }

  - if can? :destroy, answer
    = link_to 'Delete answer',
            answer_path(answer),
            method: :delete,
            remote: true,
            class: 'btn btn-danger btn-sm'

  - if can? :update, answer
    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" }, local: false do |f|
      = f.label :body, 'Your answer'
      = f.text_area :body
      = f.label :files
      = f.file_field :files, class: 'form-control', multiple: true, direct_upload: true
      = render 'links/form', resource: answer, f: f

      = f.submit 'Save'

app/views/answers/_answer_channel.html.slim
id="answer-#{answer.id}"
- if answer.persisted? && answer&.not_best_of?(question)

  p= answer.body

  .vote
    .rating id="rating-#{answer.class.name.underscore}-#{answer.id}"
      = "Rating: #{answer.rating}"

  .links
    - if answer.links.present?
      p Links:
      ul
        - answer.links.each do |link|
          id="link_#{link.id}"
          - if link.gist?
            li= link_to link.name, link.url, target: '_blank'
            - link.read_gist.each do |file, content|
              = content.content
          - else
            li= link_to link.name, link.url, target: '_blank'

  - if answer.files.attached?
    - answer.files.each do |file|
      p id="attachment_#{file.id}"
        = link_to file.filename.to_s, url_for(file), target: :blank

  .answer-comments id="answer-comments-#{answer.id}"
    h4 Comments:
    = render answer.comments
  - if current_user
    = render 'comments/form_answer', answer: answer

app/views/answers/_best_answer.html.slim
.data-best-answer
  .data-answer
    - if resource&.persisted?
      p= resource.body
      p= 'The best answer'

      = render 'shared/vote', resource: resource
      = render 'links/link', resource: resource

      - if answer.files.attached?
        - answer.files.each do |file|
          p= link_to file.filename.to_s, url_for(file)

      - if can? :update, resource
        p= link_to 'Delete the answer', answer_path(resource), class: 'destroy-answer-link', method: :delete,
                data: { answer_id: resource.id, remote: true, type: 'json' }
        p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: resource.id }

        = form_with model: resource, class: 'hidden', html: { id: "edit-answer-#{resource.id}" }, local: false do |form|
          = form.label :body, 'Your answer'
          = form.text_area :body
          = form.submit 'Save'

app/views/answers/_form.html.slim
.answer-errors

div
  = form_with model: [question, answer], class: 'new-answer', data: { type: :json } do |form|
    div
      = form.label :body
      = form.text_area :body
    div
      = form.label :files
      = form.file_field :files, multiple: true

    .answer-links
      = render 'links/form', resource: @answer, form: form

    = form.submit "Create"

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');
<% if answer.persisted? %>
  $('.new-answer #answer_body').val('');
  $('.new_name').val('');
  $('.new_url').val('');
  $('.nested-fields').remove();
<% end %>

app/views/answers/create_comment.js.erb
<% if @comment.persisted? %>
$('.form-answer-comment #comment_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.answers').html('<%= j render question.answers %>');

app/views/answers/index.html.slim
- if @answers
  - @answers.each do |answer|
    p = answer.body
    br

app/views/answers/mark_as_best.js.erb
$('.answers').html('<%= j render 'answers/best_answer', resource: @question.best_answer %>');
$('.answers').append('<%= j render @other_answers %>');

app/views/answers/new.html.slim
h1 Создать ответ

= render 'form'

= link_to 'назад', questions_path

app/views/answers/show.html.slim
h1 Ответ

p = answer.body

= link_to 'назад', questions_path

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: answer %>');
<% if !answer.errors.present? %>
  $('.answers').html('<%= j render question.answers %>');
<% end %>